//8
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 
#region GPL-2.0+ARR
/*
 * GimbalTrim (TRIM) for Kerbal Space Program
 * 
 * Copyright (c) 2014 Sébastien GAGGINI AKA Sarbian, France
 * Copyright (c) 2020, 2023 zer0Kerbal
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at
 * your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
*/
#endregion
using System.Reflection;

[assembly: AssemblyFileVersion("1.1.99.8")]
[assembly: AssemblyVersion("1.1.99.1")]
[assembly: AssemblyInformationalVersion("1.1.99")]
[assembly: KSPAssembly("GimbalTrim", 1,1,99)]

namespace GimbalTrim
{
	/// <summary>Version - retrieved at compile from GimbalTrim.version</summary>
	public static class Version
	{
		/// <summary>Major revision</summary>
		public const int major = 1;
		/// <summary>Minor revision</summary>
		public const int minor = 1;
		/// <summary>Patch revision</summary>
		public const int patch = 99;
		/// <summary>Build revision</summary>
		public const int build = 1;
		/// <summary>Version String const</summary>
		public const string Number = "1.1.99.1";
#if DEBUG
		/// <summary>Debug Version String const</summary>
        public const string Text = Number + "-zed'K BETA DEBUG";
		/// <summary>Debug SVersion String const</summary>
        public const string SText = Number + "-zed'K BETA DEBUG";
#else
		/// <summary>Text Version String const</summary>
        public const string Text = Number + "-zed'K";
		/// <summary>Plain Text Version String const</summary>
		public const string SText = Number;
#endif
	}
}